-- phpMyAdmin SQL Dump
-- version 3.3.9
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Nov 19, 2016 at 01:12 PM
-- Server version: 5.5.8
-- PHP Version: 5.3.5

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `classicauto`
--

-- --------------------------------------------------------

--
-- Table structure for table `car_details`
--

CREATE TABLE IF NOT EXISTS `car_details` (
  `Sl_no` int(100) NOT NULL AUTO_INCREMENT,
  `Brand` varchar(20) NOT NULL,
  `Model` varchar(50) NOT NULL,
  `Model2` varchar(50) NOT NULL,
  `Description` text NOT NULL,
  `Image_name` varchar(100) NOT NULL,
  `Fuel_type` varchar(20) NOT NULL,
  `Body_type` varchar(20) NOT NULL,
  `Engine_displacement` varchar(20) NOT NULL,
  `Transmission` varchar(20) NOT NULL,
  `No_of_gears` int(10) NOT NULL,
  `Power` varchar(20) NOT NULL,
  `Torque` varchar(20) NOT NULL,
  `Mileage_city` varchar(20) NOT NULL,
  `Drive_type` varchar(20) NOT NULL,
  `Top_speed` varchar(20) NOT NULL,
  `Fuel_capacity_litre` varchar(20) NOT NULL,
  `Seating_capacity` int(10) NOT NULL DEFAULT '5',
  `Colours` varchar(50) NOT NULL,
  `Price` int(50) NOT NULL,
  `Air_conditioning` varchar(10) NOT NULL DEFAULT 'Optional',
  `Power_streering` varchar(10) NOT NULL DEFAULT 'Yes',
  `Navigation_system` varchar(10) NOT NULL DEFAULT 'Yes',
  `Video_system` varchar(10) NOT NULL DEFAULT 'Yes',
  `Sunroof` varchar(10) NOT NULL DEFAULT 'No',
  `Leather_seats` varchar(10) NOT NULL DEFAULT 'Yes',
  `Electronic_mirrors` varchar(10) NOT NULL DEFAULT 'Yes',
  `Central_locking` varchar(10) NOT NULL DEFAULT 'No',
  `Anti_lock_breaking_system` varchar(10) NOT NULL DEFAULT 'Yes',
  `Airbag` varchar(10) NOT NULL DEFAULT 'Yes',
  `Parking_sensors` varchar(10) NOT NULL DEFAULT 'Yes',
  `Traction_control` varchar(10) NOT NULL DEFAULT 'No',
  `Length` varchar(10) NOT NULL,
  `Width` varchar(10) NOT NULL,
  `Height` varchar(10) NOT NULL,
  `Ground_clearance` varchar(10) NOT NULL,
  PRIMARY KEY (`Sl_no`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=37 ;

--
-- Dumping data for table `car_details`
--

INSERT INTO `car_details` (`Sl_no`, `Brand`, `Model`, `Model2`, `Description`, `Image_name`, `Fuel_type`, `Body_type`, `Engine_displacement`, `Transmission`, `No_of_gears`, `Power`, `Torque`, `Mileage_city`, `Drive_type`, `Top_speed`, `Fuel_capacity_litre`, `Seating_capacity`, `Colours`, `Price`, `Air_conditioning`, `Power_streering`, `Navigation_system`, `Video_system`, `Sunroof`, `Leather_seats`, `Electronic_mirrors`, `Central_locking`, `Anti_lock_breaking_system`, `Airbag`, `Parking_sensors`, `Traction_control`, `Length`, `Width`, `Height`, `Ground_clearance`) VALUES
(1, 'Audi', 'A3', '40 TFSI', 'Audi launched the A3 for the Indian market on December 11, 2014. Based on the hard top A3 sedan, the two-door, four-seater vehicle with a retractable roof top is targeted at consumers looking for joy and style while driving with the roof down. The German carmaker showcased the car at the Indian Auto Expo at the start of this year.\r\n\r\nThe A3 Cabriolet is sportier than the A3 sedan and has a large wheelbase. The fascia sports a single frame radiator grille surrounded by the flat xenon headlamps. Further down, the bumper gives it a sharp and sporty look. This car being a soft top gets an aluminium windscreen frame with another aluminium strip that runs around the roof aperture. The two doors and the new design of the alloy wheels set the Cabriolet apart from the four-door A3 sedan.', 'audi_a3_40_tfsi', 'Petrol', 'Sedan', '1798 cc', 'Automatic', 7, '180 PS', '250 Nm', '16 Kmpl', 'FWD', '250 Kmph', '50 Liters', 5, 'Red, White', 2790000, 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', '4456 mm', '1796 mm', '1416 mm', 'NA'),
(3, 'Jaguar', 'XJ', '3L', 'The XJ L is the flagship sedan from the Tata-owned British marque - Jaguar. The luxury sedan was launched in India in 2012, three years after its global debut and has received regular upgrades with the new model years.\r\n\r\nThe XJL has all the features that one could ever imagine in a luxury sedan. It comes with an automatic four-zone climate control, cruise control with Automatic Speed Limiter (ASL) and a three-spoke leather steering column. Steering position is electrically adjustable for height and reach with entry and exit tilt-away. Other highlights are the Jaguar Smart Key System with keyless entry and start, door puddle lamps, Phosphor Blue Halo Illumination and Interior Mood Lighting, rain sensing windscreen wipers and heated windscreen and rear window.\r\n\r\nThe XJL is the flagship model from Jaguar and the automaker has left no stone unturned to provide a consumer with the perfect combination of comfort and driving pleasure. The car rivals the Mercedes-Benz S-Class, BMW 7 Series and the Audi A8L in the Indian market.', 'jaguar_xj_3l', 'Diesel', 'Sedan', '2993 cc', 'Automatic', 8, '300.48 PS', '700 Nm', 'NA', 'RWD', '250', '83 litres', 5, 'Black, Grey', 10076244, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', '5255 mm', '2105 mm', '1460 mm', '127 mm'),
(4, 'Mercedes-Benz', 'SLC', '43 AMG', 'Mercedes has had a history of building great convertibles including the iconic SL series. With the new nomenclature coming in and Mercedes trying to index its million models, the pretty lovable SLK has now become the SLC. The first SLC that will come to India is the SLC 43 AMG, the fastest SLC built till date.\r\n\r\nThe SLC 43 AMG is powered by the 3.0-litre twin-turbocharged petrol V6 engine that develops 367bhp of power and is mated to a nine-speed automatic gearbox. While it may seem a far cry from the naturally aspirated V8 from the SLK 55 AMG, Mercedes claims that the 43 AMG is as fast as the previous generation car. It comes with Eco, Comfort, Sport and Sport+ driving modes.\r\n\r\nIt takes up the now prevalent new Mercedes fascia of the curved rectangular grille and the LED projector headlamps. It gets the diamond grille, similar to the one that debuted with the A-Class hatchback. The slit on the front fender and the breathers on the hood give the SLC a sporty look.', 'mercedes_benz_slc_43_amg', 'Petrol', 'Cabriolet', '2996 cc', 'Automatic', 9, '372 PS', '520 Nm', 'NA', 'RWD', '250', '70 Liters', 2, 'Grey, Red', 7750000, 'Optional', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', '4142 mm', '1817 mm', '1304 mm', 'NA'),
(5, 'BMW', 'i8', 'Petrol', 'BMW stunned the world in early 2011 when it announced the i division for hybrid cars and electric vehicles. The first car to come out of this development was the i3 pure electric car and then the i8 plug-in hybrid.\r\n\r\nDuring the 2014 Auto Expo, BMW under the auspices of master blaster Sachin Tendulkar unveiled the i8 plug-in hybrid. It has been on sale in the Indian market since February 2015 and is available in a single variant.\r\n\r\nThe external design of the BMW i8 harks back to that of the 8 Series range of cars that were sold in the late 1980s and early 1990s. This design comprises a low slung body style, large hood and stubby back, something that the i8 has managed to embody and yet, still look modern as possible. The i8 gets the standard BMW interior with a few space age touches like the digital gauges and what appears to be a 10-inch display to interact with the iDrive system.', 'bmw_i8_coupe', 'Petrol', 'Coupe', '1499 cc', 'Automatic', 6, '234.21 PS', '320 Nm', '47.5 kmpl', 'RWD', '250', '30 Liters', 4, 'Black, Dark blue', 21400000, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', '4689 mm', '1942 mm', '1298 mm', '117  mm'),
(6, 'Volkswagen', 'GTI', '1.8', 'The GTI has finally graced the Indian shores. The first GTI to be brought here is the Volkswagen GTI, a souped-up 3-door version of the Volkswagen Polo. We all know that when a Volkswagen gets the GTI badge, it is focussed and fast. Now that the famed GTI badge is officially here after 40 years since its inception, the hot hatch enthusiasts will be grinning ear to ear.\r\n\r\nIt is the Polo GTI which is being imported as a CBU. The headlamp shape remains the same but get integrated LED DRLs. It gets the signature GTI mesh grille and gets a new sharper bumper that sports a wide mesh air-dam with integrated fog lamps.\r\n\r\nThe GTI will be based on the top-spec Highline variant of the Polo. It gets manual height adjustable driver seat, electrically adjustable and folding mirrors and cruise control.', 'volkswagen_gti_1_8', 'Petrol', 'Hatchback', '1798 cc', 'Automatic', 7, '192 PS', '250 Nm', '16 Kmpl', 'FWD', 'NA', '45 Litres', 5, 'White, Grey', 2566539, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', '3976 mm', '1682 mm', '1452 mm', '2468 mm'),
(7, 'Audi', 'R8', 'V10 Plus', 'The new R8, as Audi claims, is the closest thing to a racing car than anything it has attempted to make for the road. This car has shed more than 45kgs compared to the outgoing model.\r\n\r\nThe design lines of the new generation R8 is all about sharpness when compared to the old car. Every design line, both front and rear has a sharp bend instead of the curves the earlier model sported. This translates into an aggressive appearance, and the wider, lower and a bit shorter dimensions gives it is a stance that lends it a more intense look.\r\n\r\nThe highlight of the new R8''s interiors is the huge curved arch of that borders the centre console and door pad around the driver''s seat and steering wheel which has been done to give the looks of being inside a race car.', 'audi_r8_v10_plus', 'Petrol', 'Fastback', '5204 cc', 'S tronic', 7, '610 PS', '540 Nm', '7 Kmpl', 'AWD', '330 Kmph', '73 Liters', 2, 'Red, Orange', 26021000, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', '4426 mm', '1940 mm', '1240 mm', '2650 mm'),
(9, 'Jaguar', 'F Pace', 'Pure', 'Known for making exquisite luxury sedans and breath taking super sports cars, British car major, Jaguar has entered the luxury SUV space with its F-Pace crossover.\r\n\r\nFor true Jag lovers, it is good news as the zesty manufacturer has not made drastic changes on the production model compared to its concept prototype. It gets the signature radiator grille with a chrome interlinked mesh and a screaming Jaguar logo in the centre. Inspired by the F-Type, the F-Pace does not tend to cling on bulk and instead brings in a sleek modern-meets-contemporary athletic design. On the side, the multi-spoke alloy wheels, flared wheel arches and a well sculpted shoulder line make it look fast. The rear is a clear give away of its inspiration from F-Type with sleek tail lamps running along the width.\r\n\r\nIn terms of performance, the F-Pace comes with two diesel engine options - the 2.0-litre inline four turbodiesel and the 3.0-litre V6 turbocharged engine.', 'jaguar_f_pace_pure', 'Diesel', 'Hatchback', '2993 cc', 'Automatic', 8, '179.47 PS', '430 Nm', '17 Kmpl', 'AWD', '208 Kmph', '60 Litres', 5, 'Blue', 6917000, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', '4731 mm', '2175 mm', '1651 mm', '213 mm'),
(10, 'Mercedes-Benz', 'A-Class', 'A 180', 'The Mercedes-Benz production lines will soon be bringing the A-Class out, albeit with a little nip and tuck. The A-Class was launched in 2013 and now two years later, the premium hatchback gets a mid-life facelift. Globally the car is already on the sale, and now the Indian market will be seeing the car enter the market on December 8.\r\n\r\nThe A-Class facelift gets new trims for the dashboard, the display remains in the centre of the dash while the car now sports a new instrument cluster and a new display for the infotainment system. The infotainment system can link to Apple and Android devices and covers phone connectivity, navigation and music. It will also be easier to use.\r\n\r\nOne can look for a new arrow-shaped front bumper, the same diamond-patterned front grille, new LED headlamps carried over from the A45 AMG, different rear light clusters to highlight the sporty character of the car and stylish rear-integrated tailpipes.', 'mercedes_benz_a-class_a_180', 'Petrol', 'Hatchback', '1595 cc', 'Automatic', 7, '123.69 PS', '200 Nm', '13 Kmpl', 'FWD', '202 Kmph', '50 Liters', 5, 'Green', 2793800, 'Automatic', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', '4299 mm', '1780 mm', '1433 mm', 'NA'),
(11, 'BMW', 'X6', 'xDrive40d M Sport', 'The ''M'' badges on this car is a bit confusing. In my head, a BMW with an M emblem stands for supercar performance and handling in a subtle looking family friendly body. A brief glance at the X6M makes you think, how in the world both these fat and intimidating SUVs will justify being  sporty or fun to drive. But on closer inspection there are hints at what''s cooking under the skin. The large front air intakes and bigger kidney grille gives both these cars an added sporty element and in profile the large beautifully crafted wheels dominate.\r\n\r\nThe X6 M looks even more sporty when viewed in profile thanks to the coupe-like roofline. At the rear the trademark M four-tailpipe exhaust, the sportscar-like diffuser and the fat rear tyres make them look intimidating even when standing still. But it''s under the bonnet that the hidden party trick of any M vehicle lies.', 'bmw_x6_xdrive_40d_m_sport', 'Diesel', 'Hardtop', '2993 cc', 'Automatic', 8, '312.71 PS', '630 NM', '15 Kmpl', 'AWD', '240 Kmph', 'NA', 5, 'Maroon, Black', 12050000, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', '4909 mm', '1989 mm', '1702 mm', '212 mm'),
(12, 'Volkswagen', 'Vento 1.6', 'MPI Trendline', 'The Volkswagen Vento has been around for quite some time. The Vento now gets a re-profiled bonnet with deeper creases and new front grille with triple chrome slats. There''s also a new front air dam and front fog lamps with integrated cornering lights. Move onto the rear and you will notice the old layout of the taillights albeit with revised internals, a thin chrome strip on the boot lid and a restyled rear bumper with chrome inserts and reflectors.\r\n\r\nThe design of the interior remains the same as before, but Volkswagen has introduced new colour themes and updated the equipment list according to the trim level. The Vento gets cruise control, cooled glove box and a dead pedal as all-new equipment. Standard features, meanwhile, include climate control, rear parking sensors, electrically adjustable rear view mirrors, ABS, twin airbags and a rather good sounding audio system with Bluetooth connectivity.', 'volkswagen_vento_1_6_mpi_trendline', 'Petrol', 'Sedan', '1598 cc', 'Manual', 5, '105 PS', '153 Nm', '16 Kmpl', 'FWD', 'NA', '55 Liters', 5, 'Silver', 823874, 'Optional', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'No', 'No', 'Yes', 'Yes', 'No', '4390 mm', '1699 mm', '1467 mm', '163 mm'),
(13, 'Audi', 'Q3', '30 TDI S', 'The launch of the Audi Q3 in 2012 was perhaps the watershed for the entry-level luxury cars in India. Of course, the BMW X1 was already on sale for a couple of years, but the real change came with this compact SUV from Audi.\r\n\r\nThe basic layout of the cabin hasn''t changed in the facelift, but there are a few additions both in terms of the design and features. There are new aluminium inserts for the dashboard, gearlever and the door trim; these add some spark to the  otherwise bland looking interior.\r\n\r\nSince this is a facelift, unsurprisingly, there are no mechanical changes in the new Audi Q3. It continues to derive power from the reliable 2.0-litre TDI engine as same as old version.', 'audi_q3_30_tdi_s', 'Diesel', 'Hatchback', '1968 cc', 'Manual', 6, '140.04 PS', '320 Nm', '17 Kmpl', 'FWD', '202 Kmph', '64 Liters', 5, 'Red, Grey', 3136000, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', '4388 mm', '1831 mm', '1608 mm', '170 mm'),
(14, 'BMW', 'X1', 'M Sport xDrive 20D', 'The BMW X1 was long due for an upgrade and the next-gen variant of the crossover has been officially unveiled at the 2016 Auto Expo held in Greater Noida. It is the second generation of the X1, and for the first time is based on a new front-wheel-drive UKL architecture.\r\n\r\nWith a heavy dose of styling, this is for the first time that the X1 is offered as an FWD car with a new platform. The X1 not just looks big but is larger and taller while carrying forward the X family''s legacy. \r\n\r\nThe BMW X1 will go up against the Mercedes-Benz GLA, the Audi Q3, the Mini Countryman and the Volvo V40 Cross Country in the compact luxury SUV segment.', 'bmw_x1_m_sport_xdrive_20d', 'Diesel', 'Hatchback', '1995 cc', 'Automatic', 8, '192.64 PS', '400 Nm', '20 Kmpl', 'AWD', '219 Kmph', '61 Liters', 5, 'Blue, White', 2990000, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', '4439 mm', '2060 mm', '1612 mm', '165 mm'),
(15, 'Audi', 'A6', '35 TDI Matrix', 'The Audi A6 Matrix is the updated version of the luxury sedan, launched in August 2015. The A6 now, is available in a single version with a diesel engine and all the features that were once part of the option pack.\r\n\r\nThe most noticeable aspect of this car is that the Matrix headlamps are standard. The technology uses multiple light sources that work coherently with the front camera to provide sufficient illuminations without blinding the oncoming traffic. The signature LED DRLs of the previous model have also been replaced by much straighter and bolder day-time running lamps.\r\n\r\nThe changes also extend to the cabin where it gets a new inbuilt infotainment system, MMI touch interface of Audi navigation system, power retractable monitors and an LTE port that offers online services from apps.', 'audi_a6_35_tdi_matrix', 'Diesel', 'Sedan', '1968 cc', 'Automatic', 7, '190.35 PS', '400 Nm', '18 Kmpl', 'FWD', '232 Kmph', '75 litres', 5, 'Blue, White', 5149000, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', '4933 mm', '1874 mm', '1455 mm', '165 mm'),
(16, 'Volkswagen', 'Ameo', '1.2 MPI Tredline', 'The Ameo is the new compact sedan from Volkswagen. Based on the Polo, the new model will be just under four metres in length to compete with the Hyundai Xcent, Honda Amaze and the Tata Zest.\r\n\r\nIn terms of looks, the Ameo will follow the traditional VW design which is subtle yet elegant. The front fascia of the Ameo is very similar to that of the Polo with the twin slat grille and a chrome underline and rectangular fog lamps. The profile is identical to the Polo till the C-pillar. The Ameo''s C-pillar has been thinned out with a quarter-glass added to make it feel roomy. The stubby boot fits the four-metre bill, but doesn''t gel with the overall flow of the design. The tail lamps are similar to the Vento but with a kink on the inner side.\r\n\r\nThe interior has been carried over straight from the Polo. The top of the dashboard is black, while rest of the trim is beige to make the cabin look roomier.', 'volkswagen_ameo_1_2_mpi_tredline', 'Petrol', 'Sedan', '1198 cc', 'Manual', 5, '75bhp', '110Nm', '17 Kmpl', 'FWD', 'NA', '45 Ltrs', 5, 'Blue', 534518, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', '3995 mm', '1682 mm', '1483 mm', '165 mm'),
(17, 'Mercedes-Benz', 'GLC', '220', 'Mercedes-Benz took the wraps off the production version of the GLC globally in mid-2015. This new SUV model, in essence, is the latest generation of the GLK-Class but gets the GLC name thanks to its close association with the C-Class, as per Mercedes’ new naming and model convention.\r\n\r\nStyling wise, the GLC follows Mercedes'' latest design theme and a result, the front end is reminiscent of quite a few models from the German carmaker''s existing range. Up front, the GLC looks similar to the entry-level GLA as it shares many of the external lines, curves and the avant-garde grille.\r\n\r\nThe interior looks thoroughly modern and stylish and is complete with a lot of bits taken off the C-Class and a few other Mercedes models.', 'mercedes_benz_glc_220', 'Diesel', 'Hatchback', '2143 cc', 'Automatic', 9, '172 PS', '400 Nm', '19 Kmpl', 'AWD', '210', '65 Liters', 5, 'Cobalt, Grey, White', 5669022, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'NA', 'NA', 'NA', '181 mm'),
(19, 'Jaguar', 'XE', 'Pure', 'Jaguar has always been known to produce cars that slot into the higher sections of the premium category and this has been evident since the new look XJ and XF began production in 2009. It has however been missing a contender in the entry-level sports segment which is dominated by cars like the BMW 3 Series, Audi A4 and the Mercedes-Benz C-Class. However, this will now change when it launches the XE sports sedan next year. Aimed at giving the British manufacturer a chance at the volumes game we can expect to see an Indian debut by the middle of next year.\r\n\r\nThe Jaguar XE, in the released publicity material and spy shots, looks exactly like the larger XF and the flagship XJ. This is a common practice among all the manufacturers partly due to economies of scale and partly due to the fact that it is easy for them to adapt a successful design across all their models to retain familiarity of product.', 'jaguar_xe_pure', 'Petrol', 'Sedan', '1999 cc', 'Automatic', 8, '199.86 PS', '320 Nm', '13 Kmpl', 'RWD', '237 Kmph', '68 Liters', 5, 'Red', 4101216, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', '4795 mm', '2075 mm', '1416 mm', 'NA'),
(20, 'BMW', 'Z4', 'sDrive 35 i', 'BMW will launch the facelifted Z4 roadster for the Indian market on November 14. It has been the mainstay of the German automaker''s CBU range. The Z4 has been on sale in India since 2009 and since then has received only one update. The 2014 Z4 is the last in this series as BMW will unveil and eventually launch an all-new Z4 next year.\r\n\r\nThe 2014 BMW Z4 gets a revised fascia in the form LED headlights, new bumper and of course the new BMW grille which debuted on the 203 3 Series last year. The side profile remains the same overall but now includes aerodynamic lines and creases for increased efficiency.\r\n\r\nThe 2014 BMW Z4''s interior remains pretty much the same as the outgoing car and is now being offered trims and an optional navigation system which includes a fold out touchscreen display.', 'bmw_z4_sdrive_35_i', 'Petrol', 'Roadster', '2979 cc', 'Automatic', 7, '310 PS', '400 Nm', '10 Kmpl', 'RWD', '250 Kmph', '55 Liters', 2, 'Grey, Red', 7750000, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', '4239 mm', '1790 mm', '1291 mm', '126 mm'),
(21, 'Audi', 'TT', '45 TFSI', 'A famed design icon, this new generation of the TT has been highly improved in terms of driving dynamics. While the previous generation models weren’t exactly the first choice of enthusiasts, the latest generation TT promises a lot with its dynamic new chassis technology and potent engines.\r\n\r\nUnlike the previous generation models, the new TT Coupe wears an aggressive look inspired by the bigger Audi R8. The MQB architecture, which also underpins a number of other Volkswagen Group cars, has made the new TT Coupe longer and wider than the outgoing car, despite shedding around 70 kilograms.\r\n\r\nThe highlighting bit inside the new TT Coupe is the state-of-the-art ''virtual cockpit'', which displays most of the information through a 12.3-inch display located behind the steering wheel. ', 'audi_tt_45_tfsi', 'Petrol', 'Sedan', '1984 cc', 'S tronic', 7, '230 PS', '370 Nm', '14 Kmpl', 'AWD', '250 Kmph', '55 Liters', 2, 'Red, Grey, White', 6494000, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', '4177 mm', '1832 mm', '1353 mm', 'NA'),
(22, 'Volkswagen', 'Jetta', '2L Highline', 'The new Jetta gets minimal updates like a redesigned front bumper, grille, headlamps with LED lights and at the rear the car gets a small kink at the top of the bootlid and new tail lamps.\r\n\r\nThe changes inside the cabin are again minimal and except the attention assist system and the new steering wheel borrowed from the Polo there is nothing to talk home about.\r\n\r\nMechanically, it will continue to be powered by the 1.4-litre TSI petrol and the 2.0-litre TDI diesel engines. The diesel is available with a choice of two transmissions - 6-speed manual and 6-speed DSG whereas the petrol is available with only the 6-speed manual.\r\n\r\nThe 2015 Jetta competes with the Toyota Corolla, Chevrolet Cruze, Hyundai Elantra and the Skoda Octavia.', 'volkswagen_jetta_2l_highline', 'Diesel', 'Sedan', '1968 cc', 'Manual', 6, '140 PS', '320 Nm', '19 Kmpl', 'FWD', '202 Kmph', '55 Liters', 5, 'Dark rose, Brown', 1495810, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', '4659 mm', '1778 mm', '1453 mm', '159 mm'),
(23, 'Mercedes-Benz', 'G-Class', 'G63 AMG', 'A piece of history that has evolved with time or at least, has attempted to. The Mercedes-Benz G 63 AMG is everything that a modern car is not; brazenly boxy, loud, jagged and as impractical as owning a full-sized fur coat for Mumbai winters. This one is called the ''crazy colour'' and it is crazy alright, but that is not just because of the way it looks.\r\n\r\nThe car is so green that it would be love at first sight for the Hulk and then they even seem to be made for each other. The street presence is awe-inspiring. All eyes on the road are glued to the G-Wagen, firstly because of the way it looks and then to try and find out what exactly is it.\r\n\r\nThe rectangular front, simple round headlamps in square console, chrome crash guard and independent turn blinkers are all the things that we have seen on the older Indian cars.', 'mercedes_benz_g_class_g63_amg', 'Petrol', 'SUV', '5461 cc', 'Automatic', 7, '551 PS', '760 Nm', '8 Kmpl', 'AWD', '210 Kmph', '96 Liters', 5, 'Brown, Green', 19968023, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', '4763 mm', '1855 mm', '1938 mm', '205 mm'),
(24, 'BMW', '3 Series', '320d Prestige', 'The BMW 3 Series has been one of the best cars to buy in the entry-level premium luxury segment for a long time. With its superior handling and space, the 3 Series used to be a winner. Now, after the new C-Class and the upcoming Audi A4, BMW has upped its ante with the new 3 Series.\r\n\r\nAs a part of its midlife makeover, the 3 Series facelift comes with subtle design upgrades to stay competitive and fresh. In terms of changes, the only visible updates come in the form of revised headlamps and a slightly altered front bumper. Globally, BMW is offering full-LED headlamps as an optional extra and they get bold ''eyebrow'' indicators.\r\n\r\nIt continues to get all the premium features like dual-zone climate control with vents for rear passenger, cruise control, power adjustable seats with memory function, electrically operated sunroof, automatic headlamps and rain sensing wipers.', 'bmw_3_series_320d_prestige', 'Diesel', 'Sedan', '1995 cc', 'Automatic', 8, '192.64 PS', '400 Nm', 'NA', 'AWD', '230 Kmph', '60 Liters', 5, 'Dark grey', 3690000, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', '4624 mm', '1811 mm', '1429 mm', '157 mm'),
(25, 'Volkswagen', 'Polo', '1.2L Trendline', 'Volkswagen launched the Polo in 2010 to compete with the Hyundai i20 in the premium hatchback segment. The German manufacturer has been tweaking the Polo regularly with cosmetic and equipment upgrades to stay abreast with the competition. Volkswagen also tinkered with idea of hot hatches with Polo GT series.\r\n\r\nThe latest string of updates on the Polo has made the signature grille a tad bit wider and it gets a chrome accent on the lower slat. The rectangular front fascia continues with the same headlamps but an added chrome strip across the length of the bumper connecting the fog lamp housings gives it more character. The side profile as well as the tail gate is the same but the tail lamp has been slightly revised to make it look modern.\r\n\r\nWhile the interior has been the same black and beige for a long time, the Polo cabin is one of the most pleasant ones in the lot. ', 'volkswagen_polo_1.2l_trendline', 'Petrol', 'Hatchback', '1198 cc', 'Manual', 5, '75 PS', '110 Nm', '16 Kmpl', 'FWD', 'NA', '45 Liters', 5, 'Brown, White', 548258, 'Optional', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', '3971 mm', '1682 mm', '1469 mm', '165 mm'),
(26, 'BMW', 'X5', 'xDrive 30D', 'BMW has been officially selling the X5 for over half a decade and in that time, it has done fairly well for the brand. Thanks to its spacious and luxurious cabin and car-like dynamics, the X5 has proved to be a successful model for BMW India.\r\n\r\nNow in its third generation, the 2014 X5 claims to be lighter, more luxurious and sportier than ever before. BMW India has launched this new model in the Indian market, hoping to replicate the success of its predecessor.\r\n\r\nDesign wise, the 2014 BMW X5 takes heavy inspiration from the rest of the BMW range. The most noticeable change is at the front-end. The F30 3-Series-inspired fascia looks much sharper than before. The rest of the design gets a similar update, giving the X5 a more aggressive look.', 'bmw_xdrive_30d', 'Diesel', 'SUV', '2993 cc', 'Automatic', 8, '262 PS', '560 Nm', '15 Kmpl', 'AWD', '223 Kmph', '85 Liters', 7, 'Brown, White', 6790000, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', '4886 mm', '1938 mm', '1772 mm', '209 mm'),
(28, 'Mercedes-Benz', 'AMG GT', 'S', 'Some cars are built such that they pass the test of time with panache. The Mercedes SL300, better known as the Gullwing, was one such. While Mercedes recreated the Gullwing in a modern avatar, the SLS AMG, something was missing. So here we have the AMG GT, the one to get the legacy of small coupes with long bonnets and a glass box placed almost on the rear wheels to seat you.\r\n\r\nTalking about small, the AMG GT is not really that small. The new two-door coupe comes in black, yellow, two shades of red, silver, grey, white and blue. Coming to the car''s body work, the German automaker''s craftsmanship and design philosophy can be clearly seen from the design of the AMG-GT. Right from characteristic styling, thoroughbred motorsport technology to the optimum weight distribution, Mercedes-Benz has brought in everything that a Merc fan would expect from an authentic Mercedes-AMG sports car.', 'mercedes_benz_amg_gt_s', 'Petrol', 'Roadster', '1198 cc', 'Manual', 5, '75 PS', '110 Nm', '16 Kmpl', 'FWD', 'NA', '45 Liters', 5, 'Black, Green', 24316800, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', '3971 mm', '1682 mm', '1469 mm', '165 mm'),
(29, 'Audi', 'RS6', 'Avant', 'The cars are focussed, incredibly fast and in most cases not exactly practical. But when it is an estate in question, like the RS6 Avant, even the concerns of practicality are taken care off.\r\n\r\nThe RS6 has been built on the Audi A6 platform. The horizontally slatted hexagonal front grille dominates the fascia. It gets the new intelligent LED matrix headlamps slotted above the wide air intakes on the bumper which also houses the round fog lamps. The RS badge with the red highlight denotes the pedigree of the mill within. The tail hatch opens upwards and the twin exhausts look aggressive with the blacked out rear splitter.\r\n\r\nThe interior is all black and upholstered in fine quality leather. The three-spoke flat bottom steering wheel is contoured for maximum grip and has steering mounted audio controls along with cruise control and paddle shifters. ', 'audi_rs6_avant', 'Petrol', 'Hatchback', '3993 cc', 'Tiptronic', 8, '560 PS', '700 Nm', '9 Kmpl', 'AWD', '305 Kmph', '65 Liters', 5, 'Red, Grey', 14448000, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', '4979 mm', '1936 mm', '1461 mm', '109 mm'),
(30, 'Volkswagen', 'Cross Polo', '1.2 MPI', 'The Volkswagen Cross Polo has been created for those looking at a premium hatchback in a sporty crossover style. Equipped with a 1.2-litre TDI engine with a maximum power output of 75 PS@ 4200rpm and a maximum torque of 180 Nm @ 2000 rpm with a 5-speed manual gearbox, the Cross Polo comes in three colours and packed with loads of features never seen before on this model\r\n\r\nVW''s Polo-based crossover aims to thrill customers with the stylish looks of its popular hatchback and the high riding position of an SUV.', 'volkswagen_cross_polo', 'Petrol', 'MUV', '1198 cc', 'Manual', 5, '75 PS', '110 Nm', '16 Kmpl', 'FWD', 'NA', '45 Liters', 5, 'Orange, Grey', 767998, 'Optional', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', '3987 mm', '1698 mm', '1483 mm', '165 mm'),
(32, 'Mercedes-Benz', 'GLS', '350 D 4MATIC', 'Mercedes-Benz has put its flagship SUV, the GL under the knife and the first noticeable change is the new name - the GLS. The seven-seater SUV will now fall in line with the German manufacturer''s new system of nomenclature where the segments are defined as A, B, C, E and S and the SUVs get the ''GL'' tag added to the segment. The GLS gets cosmetic updates both internally and externally while under the skin it is the same reliable GL.\r\n\r\nThe Mercedes-Benz GLS retains the overall shape as the current GL but gets new front and rear bumpers. The LED headlamps now resemble the S-Class and gets twin barrel headlights. The LED daytime running lamps have become a signature for the three-pointed-star. The high-mounted large front grille has been reworked with vented slats while the bash plate extends further up towards the grille as compared to the current car.', 'mercedes_benz_gls_350_d_4matic', 'Diesel', 'MUV', '2987 cc', 'Automatic', 9, '261 PS', '620 Nm', 'NA', 'NA', '222 Kmph', '100 Liters', 7, 'White', 8335627, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', '5130 mm', '1930 mm', '1850 mm', '170 mm'),
(33, 'BMW', 'M3', 'Sedan', 'The M3 serves a dual purpose role very well, one of a practical sedan most days of the week and that of a blisteringly quick sportscar when you put your foot down. It handles like a dream and catapults out of corners, all with four comfortable seats and a large enough boot. It''s the best M car you can buy.\r\n\r\nThe M3 is quick, stunning to look at and has the practicality of a sedan. It''s one of the best dual purpose cars to buy in India right now.\r\n\r\nMW''s M division has done the world a great deal of good by introducing us to the M3, the perfect driving machine for the BMW fan - fast, agile, compact and aggressive in equal measure. It''s the sedan, to my eyes, that feels better proportioned and more desirable of the two and so the M3 would be my pick over an M4.', 'bmw_m3_sedan', 'Petrol', 'Sedan', '2979 cc', 'Automatic', 7, '437 PS', '550 Nm', '10 Kmpl', 'RWD', '250 Kmph', '70 Liters', 5, 'Blue', 12550000, 'Optional', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', '4671 mm', '1877 mm', '1430 mm', 'NA'),
(34, 'Audi', 'S6', '4 TFSI Quattro', 'The Audi S6 is a cracker of a performance car that is slotted between performance executive luxury sedans and high performance executive luxury sedans both in terms of power and price. The 4.0 litre V8 TFSI petrol engine that churns out 420PS of power also features cylinder deactivation that cuts 4 cylinders under partial load to better fuel efficiency. Audi''s legendary Quattro all-wheel drive system allows the S6 to devour corners with phenomenal pace.\r\n\r\nThe Audi S models have always carried an aura of aesthetic appeal, elegance, comfort and power, so when it comes to the S6, the expectations are high as this car has to uphold Audi''s sporting legacy in a practical package.\r\n\r\nAudi S6 treads the middle line in terms of power and price between performance luxury executive saloons and high performance luxury executive saloons in the country.', 'audi_s6_4_tfsi_quattro', 'Petrol', 'Sedan', '3993 cc', 'Automatic', 7, '426 PS', '550 Nm', '13 Kmpl', 'AWD', '250 Kmph', '75 Liters', 5, 'Off white, Blue', 9757000, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', '4931 mm', '1874 mm', '1440 mm', '125 mm'),
(35, 'Volkswagen', 'Beetle', '1.4 L TSI', 'The Volkswagen Beetle is a legendary car. In the eight decades since its inception, the Beetle has undergone quite a few transformations to stay abreast with the changing times. The once people''s car now commands a premium and has moved up the segments to become a lifestyle product. The updated model of the lifestyle luxury hatchback is larger than the previous model based on the PQ35 platform that it shares with the D-Segment sedan, the Jetta.\r\n\r\nThe Beetle, though, is still the old bug that it was. The iconic form with curvy lines and circular large headlamps has been retained but has become more aggressive with flared wheel arches and muscular lines. At the front, headlamps get projector units and LED DRLs; the bumper is simple with a stretched rectangular air dam with fog lamps and turn blinkers on the side.', 'volkswagen_beetle_1_4_l_tsi', 'Petrol', 'Special', '1395 cc', 'Automatic', 7, '150 PS', '250 Nm', '17 Kmpl', 'FWD', '208 Kmph', '55 Liters', 5, 'Orange, Blue', 2698010, 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', '4278 mm', '1808 mm', '1486 mm', '136 mm'),
(36, 'Mercedes-Benz', 'E-Class', 'E 200 CGI', 'Mercedes-Benz has retained the distinctive look of the older-generation E-Class (W211) on the new E350. The new angular body of the E350 looks more aggressive reminding us of the 80''s E-Class designs. Some of the recent Mercedes-Benz designs had lost the muscular look which the older Benz cars had. The designers at Mercedes-Benz have now bounced back with a sturdy-looking design for the E350.\r\n\r\nThe twin oval headlamps which had become one of the trademarks of the E-Class in the last decade have been replaced by twin parallelogram headlamps, coupled with hockey-stick shaped LED daylight running lamps. The gently curving hood of the older E-Class has been replaced with the new E350''s bonnet''s steeper rake, more prominent strakes and shut line running up to the A-pillar. The lines at the meeting point of the A-pillar, hood and the fender look mismatched.', 'mercedes_benz_e_200_cgi', 'Petrol', 'Roadster', '1991 cc', 'Automatic', 7, '183 PS', '300 Nm', '12 Kmpl', 'RWD', '233 Kmph', '80 Liters', 5, 'White', 5081560, 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', '4879 mm', '1854 mm', '1474 mm', 'NA');

-- --------------------------------------------------------

--
-- Table structure for table `news_updates`
--

CREATE TABLE IF NOT EXISTS `news_updates` (
  `sl_no` int(100) NOT NULL AUTO_INCREMENT,
  `news_header` varchar(100) NOT NULL,
  `news_body_text` text NOT NULL,
  `search_text` varchar(50) NOT NULL,
  `image_name` varchar(50) NOT NULL,
  `update_timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`sl_no`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=8 ;

--
-- Dumping data for table `news_updates`
--

INSERT INTO `news_updates` (`sl_no`, `news_header`, `news_body_text`, `search_text`, `image_name`, `update_timestamp`) VALUES
(1, 'Volkswagen GTI launched at Rs 25.6 lac', 'After showcasing it at the 2016 Auto Expo earlier this year, Volkswagen India has now launched the GTI. The Polo-based full-on hot hatch is now on sale at Rs 25.65 lakh ex-showroom, Mumbai with a limited run of just 99 cars.\r\n\r\nGlobally, the Polo GTI is offered in either three or five-door form but for the Indian market, VW India chose to bring the three-door model for exclusivity.', 'Volkswagen GTI launched at Rs 25.6 lac', 'volkswagen_news1', '2016-11-09 00:54:46'),
(2, 'Datsun Redigo Sport Version 2', 'Datsun has announced an extension of the production run of their limited edition Redigo Sport in the wake of its successful run in the market. The production has been increased to 1800 units from the 1000 units announced earlier.\r\n\r\nA thick black stripe runs through the length of the car starting from the centre of the hood and gets a pinstripe on each side.', 'Datsun Redigo Sport production extended', 'datsun_news1', '2016-11-09 00:56:09'),
(3, 'Audi reveals the A5 Cabriolet', 'Audi has revealed the new A5 Cabriolet ahead of its official debut at the 2016 Los Angeles Auto Show on November.  The new open top model shares the same design as that of the A5 Coupe and claims to be more focused on safety, driving dynamics and performance.  Audi will launch the new A5 Cabriolet in the UK in 2017. the new engines offers about 17 per cent more power than the older model.', 'Audi reveals the A5 Cabriolet', 'audi_news1', '2016-11-09 00:57:10'),
(4, 'Lamborghini and MIT to collaborate ', 'Changing times and evolving needs has encouraged super carmaker Lamborghini to sign a three-year sponsorship deal with the Massachusetts Institute of Technology (MIT) Italy.\r\n\r\nAs a result of the collaboration, Lamborghini engineers will be working with the students and the teaching staff at MIT with a common aim of presenting the next-gen of supercars.', 'Lamborghini and MIT to collaborate ', 'lamborghini_news1', '2016-11-09 00:57:47'),
(5, '2017 Nissan GT-R to be launched', 'Every car enthusiast around the world has at least once dreamt about owning the Nissan GT-R. This time around, reports indicate that the 2017 GT-R is set for its India launch on November 9. Pre-bookings for the same have already commenced against a booking amount of Rs 25 lakh. Post launch, the 2017 Nissan GT-R will compete against the likes of Porsche 911 Turbo and Audi R8V10 in India.', '2017 Nissan GT-R to be launched', 'nissan_news1', '2016-11-09 00:58:24'),
(6, 'Ferrari 458 tuned by Vorsteiner unveiled', 'This Ferrari from Vorsteiner is not about horsepower. It flaunts the latest Aero-body kit from the tuner make sure it goes faster with the same horsepower.\r\n\r\nCalled the 458-VX, it is based on the Ferrari 458 Italia. The Vorsteiner body kit makes it look spectacular, especially in the fresh white paint scheme and the golden alloys. The front bumper is custom built in carbon-fibre.', 'Ferrari 458 tuned by Vorsteiner unveiled', 'ferrari_news1', '2016-11-09 00:59:20'),
(7, 'Ford EcoSport Gets Dual Airbags', 'Ford now offers the EcoSport compact SUV with dual airbags as standard. The passive safety feature was earlier offered on the Trend variant and above. ABS with EBD, however, will still be offered with all but the base variant.\r\n\r\nThe EcoSport still has the bragging rights of offering one of the most comprehensive safety packages in the segment.', 'Ford EcoSport Gets Dual Airbags As Standard', 'ford_news1', '2016-11-09 14:20:19');

-- --------------------------------------------------------

--
-- Table structure for table `orders`
--

CREATE TABLE IF NOT EXISTS `orders` (
  `Sl_no` int(100) NOT NULL AUTO_INCREMENT,
  `Name` varchar(50) NOT NULL,
  `E_mail` varchar(50) NOT NULL,
  `Phone` varchar(50) NOT NULL,
  `Car_model` varchar(100) NOT NULL,
  `Time_stamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Task_completed` varchar(10) NOT NULL DEFAULT 'No',
  `Address` varchar(200) NOT NULL,
  `Message` text NOT NULL,
  PRIMARY KEY (`Sl_no`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=5 ;

--
-- Dumping data for table `orders`
--

INSERT INTO `orders` (`Sl_no`, `Name`, `E_mail`, `Phone`, `Car_model`, `Time_stamp`, `Task_completed`, `Address`, `Message`) VALUES
(1, 'Balram', 'balram@gmail.com', '9898989898', 'BMW X5', '2016-11-16 10:22:35', 'Yes', 'Kerala', 'Please do the needful.'),
(2, 'Tom', 'tom@gmail.com', '9999777799', 'BMW X5', '2016-11-16 11:04:24', 'Yes', 'Kannur', 'Please do the needful.'),
(3, 'Raghavan', 'raghavan@gmail.com', '4545454545', 'Mercedes-BenzÂ E-ClassÂ E 200 CGI', '2016-11-16 14:03:34', 'No', 'Kannur, Kerala, India -670001', 'Please process my order as soon as possible.\r\n                '),
(4, 'Jeemon', 'jeemon@gmail.com', '567', 'AudiÂ S6Â 4 TFSI Quattro', '2016-11-17 13:09:50', 'Yes', 'parayoola', 'Please process my order as soon as possible.\r\n                ');

-- --------------------------------------------------------

--
-- Table structure for table `userdetails`
--

CREATE TABLE IF NOT EXISTS `userdetails` (
  `Username` varchar(50) NOT NULL,
  `Password` varchar(50) NOT NULL,
  `Full_name` varchar(50) NOT NULL,
  `DOB` date NOT NULL,
  `Reg_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Access_level` varchar(20) NOT NULL DEFAULT 'User',
  PRIMARY KEY (`Username`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `userdetails`
--

INSERT INTO `userdetails` (`Username`, `Password`, `Full_name`, `DOB`, `Reg_date`, `Access_level`) VALUES
('admin', '123', 'Administrator', '1995-01-01', '2016-11-04 10:30:17', 'Administrator'),
('jeemon', '123', 'Jeemon Puthusseri', '1984-12-22', '2016-11-04 18:47:16', 'User');

-- --------------------------------------------------------

--
-- Table structure for table `web_messages`
--

CREATE TABLE IF NOT EXISTS `web_messages` (
  `Sl_no` int(100) NOT NULL AUTO_INCREMENT,
  `Name` varchar(100) NOT NULL,
  `E_mail` varchar(100) NOT NULL,
  `Message` text NOT NULL,
  `Time_stamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Task_completed` varchar(10) NOT NULL DEFAULT 'No',
  PRIMARY KEY (`Sl_no`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=4 ;

--
-- Dumping data for table `web_messages`
--

INSERT INTO `web_messages` (`Sl_no`, `Name`, `E_mail`, `Message`, `Time_stamp`, `Task_completed`) VALUES
(1, 'Raj', 'raj@gmail.com', 'Hi, Thank you for your support!', '2016-11-17 16:09:56', 'Yes'),
(2, 'Nadia', 'nadia@gmail.com', 'Please mail me your service brochure to my maid id given.', '2016-11-17 15:47:34', 'No'),
(3, 'Joesph', 'joseph@gmail.com', 'I''m interested in your service, please call me regarding the purchase.', '2016-11-17 15:47:36', 'Yes');
